apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentdconf
  namespace: development
data:
  fluent.conf: |
      <source>
        @type tail
        path /var/log/httpd-access.log
        pos_file /var/log/td-agent/httpd-access.log.pos
        tag apache.access
        <parse>
         @type apache2
        </parse>
      </source>

    #  <filter dev.myapp.applogs>
    #    @type record_transformer
    #    <record>
    #    hostname ${hostname}
    #    </record>
    #  </filter>

    #  <match apache.access>
    #    @type elasticsearch
    #    host 172.99.1.218
    #    port 59200
    #    user elasticusr
    #    password Pa$$w0rd
    #    index_name fluentd.${tag}
    #    logstash_format true
    #    logstash_prefix dev.myapp.applogs
    #    flush_interval 1s
    #  </match>

